export const communities = [
  {
    id: 'CM-4456',
    name: 'Whispering Hills',
    division: 'DFW',
    plans: 3,
    specs: 185,
    lots: 35,
    thumbnail: 'whispering-hills.png',
    planIds: ['aspen', 'woodford', 'serena'],
    totalValue: '2.1 M',
    lotsAvailable: 28,
    occupancyRate: 25,
    activeBuilds: 8,
    mapProjects: 6,
  },
  {
    id: 'CM-3341',
    name: 'Riverside Estates',
    division: 'Houston',
    plans: 3,
    specs: 185,
    lots: 48,
    thumbnail: 'riverside.png',
    planIds: ['aspen', 'woodford', 'serena'],
    totalValue: '2.6 M',
    lotsAvailable: 36,
    occupancyRate: 32,
    activeBuilds: 12,
    mapProjects: 8,
  },
  {
    id: 'CM-2198',
    name: 'The Pines',
    division: 'DFW',
    plans: 3,
    specs: 185,
    lots: 62,
    thumbnail: 'the-pines.png',
    planIds: ['aspen', 'woodford', 'serena'],
    totalValue: '3.6 M',
    lotsAvailable: 45,
    occupancyRate: 38,
    activeBuilds: 18,
    mapProjects: 12,
  },
]
