export const communities = [
  {
    id: 'silver-lake',
    name: 'Silver Lake',
    division: 'Northwest Division',
    plans: 4,
    specs: 125,
    lots: 82,
    thumbnail: 'silver-lake-thumb.png',
    planIds: ['serena', 'charlotte', 'aiden', 'davenport'],
    totalValue: '2.3 M',
    lotsAvailable: 96,
    occupancyRate: 25,
    activeBuilds: 96,
    mapProjects: 20,
  },
  {
    id: 'real-forest',
    name: 'Real Forest',
    division: 'Northwest Division',
    plans: 2,
    specs: 89,
    lots: 64,
    thumbnail: 'real-forest-thumb.png',
    planIds: ['charlotte', 'davenport'],
    totalValue: '1.8 M',
    lotsAvailable: 64,
    occupancyRate: 42,
    activeBuilds: 48,
    mapProjects: 15,
  },
]
