export interface PlanData {
  // Basic display info
  id: string
  name: string
  beds: string
  baths: string
  sqft: string
  image: string
  communityCount: number
  series: string
  specLevel: string
  modelId: string

  // Detailed specifications
  masterModelId: string
  collection: string[]
  seriesList: string[]
  structureType: string[]
  specificationLevel: string[]
  division: string[]
  description: string

  // Base house specs
  bedrooms: number
  bathrooms: number
  halfBaths: number
  garageSpaces: number
  totalFinishedSqft: number
  totalUnfinishedSqft: number
  width: string
  depth: string
  numberOfElevations: number
  foundationTypes: string[]
  costPerSquareFoot: number
  floors: number
  version: number

  // Permit & Compliance
  buildingCode: string
  permitNumber: string
  permitIssued: string
  permitExpires: string
  governingBody: string
  state: string
  adaCompliant: string

  // Plan Features
  planFeatures: string[]

  // Team
  architectOfRecord: string
  engineerOfRecord: string
  copyrightOwner: string

  // Max Configurations
  maxBedrooms: number
  maxBathrooms: number
  maxHalfBaths: number
  maxTotalFinishedSqft: number
  maxTotalUnfinishedSqft: number
  maxWidth: string
  maxDepth: string
  maxHeight: string

  // Area Breakdown
  baseAreaUnderRoof: number
  maxAreaUnderRoof: number
  firstFloorSqft: number
  secondFloorSqft: number
  frontPorchSqft: number
  garageSqft: number

  // Roof & Pitch
  minRoofPitch: string
  maxRoofPitch: string
  roofConstructionType: string

  // Interior Layout
  laundryLocation: string
  ownerRoomLocation: string
  baseGarageDoors: number
  maxGarageDoors: number
  maxGarageBay: number
  garageLocation: string
  baseFireplace: number
  maxFireplace: number
  foundationQuantity: number

  // Exterior & Finishes
  exteriorFinish: string[]
  doorTypes: string[]
  windowTypes: string[]
  differentWindowSizes: number
  baseExteriorDoors: number
  maxExteriorDoors: number
  baseInteriorDoors: number
  maxInteriorDoors: number
  wallConstructionType: string[]

  // Performance
  minCeilingHeight: number
  maxCeilingHeight: number
  energyRating: string
  hvacType: string
  plumbingType: string[]
}

export const plans: PlanData[] = [
  {
    id: 'aspen',
    name: 'The Aspen',
    beds: '3',
    baths: '2.5',
    sqft: '2,500 ft²',
    image: '/assets/plans/home-plan1.png',
    communityCount: 3,
    series: "30' Series",
    specLevel: 'Signature',
    modelId: 'MODEL-2024-001',
    masterModelId: 'MASTER-2024-001',
    collection: ['River Collection'],
    seriesList: ["30' Series"],
    structureType: ['Single Family'],
    specificationLevel: ['Signature'],
    division: ['DFW'],
    description: 'The Aspen is a beautifully designed single-story home featuring an open concept layout perfect for modern living.',
    bedrooms: 3,
    bathrooms: 2,
    halfBaths: 1,
    garageSpaces: 2,
    totalFinishedSqft: 2500,
    totalUnfinishedSqft: 400,
    width: "30'",
    depth: "50'",
    numberOfElevations: 4,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 165,
    floors: 1,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2024-003',
    permitIssued: '3/20/2024',
    permitExpires: '3/20/2027',
    governingBody: 'City of Plano',
    state: 'TX',
    adaCompliant: 'No',
    planFeatures: ['Open concept', 'Flex room', 'Energy-efficient'],
    architectOfRecord: 'Smith Architecture',
    engineerOfRecord: 'Johnson Engineering',
    copyrightOwner: 'Smith Architecture',
    maxBedrooms: 4,
    maxBathrooms: 3,
    maxHalfBaths: 1,
    maxTotalFinishedSqft: 2800,
    maxTotalUnfinishedSqft: 400,
    maxWidth: "30'",
    maxDepth: "50'",
    maxHeight: "35'",
    baseAreaUnderRoof: 1800,
    maxAreaUnderRoof: 2200,
    firstFloorSqft: 2500,
    secondFloorSqft: 0,
    frontPorchSqft: 280,
    garageSqft: 440,
    minRoofPitch: '8/12',
    maxRoofPitch: '4/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Down',
    ownerRoomLocation: 'Down',
    baseGarageDoors: 1,
    maxGarageDoors: 1,
    maxGarageBay: 2,
    garageLocation: 'Front',
    baseFireplace: 1,
    maxFireplace: 1,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Brick/Brick Accent'],
    doorTypes: ['6 Panel', 'Steel / Craftsman'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 6,
    baseExteriorDoors: 2,
    maxExteriorDoors: 2,
    baseInteriorDoors: 6,
    maxInteriorDoors: 8,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 12,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'woodford',
    name: 'The Woodford',
    beds: '3',
    baths: '2.5',
    sqft: '2,600 ft²',
    image: '/assets/plans/home-plan2.png',
    communityCount: 3,
    series: "40' Series",
    specLevel: 'Premium',
    modelId: 'MODEL-2025-002',
    masterModelId: 'MASTER-2025-002',
    collection: ['Heritage Collection'],
    seriesList: ["40' Series"],
    structureType: ['Single Family'],
    specificationLevel: ['Premium'],
    division: ['DFW', 'Houston'],
    description: 'The Woodford offers timeless design with modern amenities, featuring spacious living areas and premium finishes throughout.',
    bedrooms: 3,
    bathrooms: 2,
    halfBaths: 1,
    garageSpaces: 2,
    totalFinishedSqft: 2600,
    totalUnfinishedSqft: 450,
    width: "40'",
    depth: "55'",
    numberOfElevations: 4,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 175,
    floors: 1,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2025-002',
    permitIssued: '1/15/2025',
    permitExpires: '1/15/2028',
    governingBody: 'City of Arlington',
    state: 'TX',
    adaCompliant: 'No',
    planFeatures: ['Covered patio', 'Study', 'Walk-in pantry'],
    architectOfRecord: 'JB Designs',
    engineerOfRecord: 'Apex Structural Engineering',
    copyrightOwner: 'JB Designs',
    maxBedrooms: 4,
    maxBathrooms: 3,
    maxHalfBaths: 1,
    maxTotalFinishedSqft: 2900,
    maxTotalUnfinishedSqft: 450,
    maxWidth: "40'",
    maxDepth: "55'",
    maxHeight: "36'",
    baseAreaUnderRoof: 1900,
    maxAreaUnderRoof: 2300,
    firstFloorSqft: 2600,
    secondFloorSqft: 0,
    frontPorchSqft: 320,
    garageSqft: 480,
    minRoofPitch: '8/12',
    maxRoofPitch: '4/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Down',
    ownerRoomLocation: 'Down',
    baseGarageDoors: 1,
    maxGarageDoors: 2,
    maxGarageBay: 2,
    garageLocation: 'Front',
    baseFireplace: 1,
    maxFireplace: 1,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Stone Accent'],
    doorTypes: ['6 Panel', 'Steel / Craftsman'],
    windowTypes: ['Double Pane'],
    differentWindowSizes: 5,
    baseExteriorDoors: 2,
    maxExteriorDoors: 3,
    baseInteriorDoors: 7,
    maxInteriorDoors: 9,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 14,
    energyRating: 'Energy Star',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'serena',
    name: 'The Serena',
    beds: '4',
    baths: '3.5',
    sqft: '3,200 ft²',
    image: '/assets/plans/home-plan3.png',
    communityCount: 3,
    series: "50' Series",
    specLevel: 'Luxury',
    modelId: 'MODEL-2023-001',
    masterModelId: 'MASTER-2023-001',
    collection: ['Luxury Collection'],
    seriesList: ["50' Series"],
    structureType: ['Single Family', 'Villa'],
    specificationLevel: ['Luxury'],
    division: ['DFW', 'Houston', 'Austin'],
    description: 'The Serena represents the pinnacle of luxury living with expansive spaces, premium finishes, and thoughtful design details.',
    bedrooms: 4,
    bathrooms: 3,
    halfBaths: 1,
    garageSpaces: 3,
    totalFinishedSqft: 3200,
    totalUnfinishedSqft: 600,
    width: "50'",
    depth: "60'",
    numberOfElevations: 5,
    foundationTypes: ['Slab', 'Pier and Beam'],
    costPerSquareFoot: 195,
    floors: 2,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2023-001',
    permitIssued: '8/10/2023',
    permitExpires: '8/10/2026',
    governingBody: 'City of Frisco',
    state: 'TX',
    adaCompliant: 'Partial',
    planFeatures: ['Grand foyer', 'Game room', 'Outdoor kitchen'],
    architectOfRecord: 'Emerald Design Group',
    engineerOfRecord: 'Horizon Engineering',
    copyrightOwner: 'Emerald Design Group',
    maxBedrooms: 5,
    maxBathrooms: 4,
    maxHalfBaths: 2,
    maxTotalFinishedSqft: 3600,
    maxTotalUnfinishedSqft: 700,
    maxWidth: "50'",
    maxDepth: "65'",
    maxHeight: "40'",
    baseAreaUnderRoof: 2400,
    maxAreaUnderRoof: 3000,
    firstFloorSqft: 1800,
    secondFloorSqft: 1400,
    frontPorchSqft: 350,
    garageSqft: 680,
    minRoofPitch: '10/12',
    maxRoofPitch: '6/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Up',
    ownerRoomLocation: 'Down',
    baseGarageDoors: 2,
    maxGarageDoors: 2,
    maxGarageBay: 3,
    garageLocation: 'Side',
    baseFireplace: 1,
    maxFireplace: 2,
    foundationQuantity: 1,
    exteriorFinish: ['Brick', 'Stone', 'Stucco'],
    doorTypes: ['Custom', 'Steel / Craftsman'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 8,
    baseExteriorDoors: 3,
    maxExteriorDoors: 4,
    baseInteriorDoors: 10,
    maxInteriorDoors: 14,
    wallConstructionType: ['2x6'],
    minCeilingHeight: 10,
    maxCeilingHeight: 20,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'liam',
    name: 'The Liam',
    beds: '3',
    baths: '2',
    sqft: '2,500 ft²',
    image: '/assets/plans/home-plan4.png',
    communityCount: 2,
    series: "30' Series",
    specLevel: 'Signature',
    modelId: 'MODEL-2024-002',
    masterModelId: 'MASTER-2024-002',
    collection: ['River Collection'],
    seriesList: ["30' Series"],
    structureType: ['Single Family'],
    specificationLevel: ['Live.M'],
    division: ['DFW'],
    description: 'Open concept, flex room, energy-efficient single-story living designed for modern families.',
    bedrooms: 3,
    bathrooms: 2,
    halfBaths: 1,
    garageSpaces: 2,
    totalFinishedSqft: 2500,
    totalUnfinishedSqft: 500,
    width: "30'",
    depth: "50'",
    numberOfElevations: 4,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 155,
    floors: 1,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2024-001',
    permitIssued: '6/15/2024',
    permitExpires: '6/15/2027',
    governingBody: 'City of Frisco',
    state: 'TX',
    adaCompliant: 'No',
    planFeatures: ['Open concept', 'Flex room', 'Energy-efficient'],
    architectOfRecord: 'Smith Architecture',
    engineerOfRecord: 'Johnson Engineering',
    copyrightOwner: 'Smith Architecture',
    maxBedrooms: 4,
    maxBathrooms: 3,
    maxHalfBaths: 1,
    maxTotalFinishedSqft: 2800,
    maxTotalUnfinishedSqft: 500,
    maxWidth: "30'",
    maxDepth: "50'",
    maxHeight: "35'",
    baseAreaUnderRoof: 1800,
    maxAreaUnderRoof: 2200,
    firstFloorSqft: 2500,
    secondFloorSqft: 0,
    frontPorchSqft: 300,
    garageSqft: 120,
    minRoofPitch: '8/12',
    maxRoofPitch: '4/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Down',
    ownerRoomLocation: 'Down',
    baseGarageDoors: 1,
    maxGarageDoors: 1,
    maxGarageBay: 2,
    garageLocation: 'Front',
    baseFireplace: 1,
    maxFireplace: 1,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Brick/Brick Accent'],
    doorTypes: ['6 Panel', 'Steel / Craftsman'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 6,
    baseExteriorDoors: 2,
    maxExteriorDoors: 2,
    baseInteriorDoors: 6,
    maxInteriorDoors: 8,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 12,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'farmhouse',
    name: 'The Farmhouse',
    beds: '4',
    baths: '3',
    sqft: '3,200 ft²',
    image: '/assets/plans/home-plan5.png',
    communityCount: 4,
    series: "50' Series",
    specLevel: 'Premium',
    modelId: 'MODEL-2023-016',
    masterModelId: 'MASTER-2023-016',
    collection: ['Heritage Collection'],
    seriesList: ["50' Series"],
    structureType: ['Single Family'],
    specificationLevel: ['Premium'],
    division: ['DFW', 'Houston'],
    description: 'Farmhouse modern design featuring a chef\'s island and expansive outdoor living spaces.',
    bedrooms: 4,
    bathrooms: 3,
    halfBaths: 1,
    garageSpaces: 3,
    totalFinishedSqft: 3200,
    totalUnfinishedSqft: 980,
    width: "50'",
    depth: "60'",
    numberOfElevations: 5,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 195,
    floors: 2,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2023-016',
    permitIssued: '11/10/2023',
    permitExpires: '11/10/2026',
    governingBody: 'City of McKinney',
    state: 'TX',
    adaCompliant: 'No',
    planFeatures: ['Farmhouse modern', "Chef's island", 'Outdoor living'],
    architectOfRecord: 'JB Designs',
    engineerOfRecord: 'Apex Structural Engineering',
    copyrightOwner: 'JB Designs',
    maxBedrooms: 5,
    maxBathrooms: 4,
    maxHalfBaths: 2,
    maxTotalFinishedSqft: 3400,
    maxTotalUnfinishedSqft: 980,
    maxWidth: "50'",
    maxDepth: "60'",
    maxHeight: "40'",
    baseAreaUnderRoof: 2400,
    maxAreaUnderRoof: 3200,
    firstFloorSqft: 2000,
    secondFloorSqft: 1400,
    frontPorchSqft: 200,
    garageSqft: 1000,
    minRoofPitch: '10/12',
    maxRoofPitch: '6/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Up',
    ownerRoomLocation: 'Up',
    baseGarageDoors: 1,
    maxGarageDoors: 2,
    maxGarageBay: 3,
    garageLocation: 'Side',
    baseFireplace: 1,
    maxFireplace: 2,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Brick/Copper Accent'],
    doorTypes: ['6 Panel', 'Copper/Custom'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 8,
    baseExteriorDoors: 2,
    maxExteriorDoors: 2,
    baseInteriorDoors: 8,
    maxInteriorDoors: 10,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 20,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'ashley',
    name: 'The Ashley',
    beds: '4',
    baths: '3',
    sqft: '2,950 ft²',
    image: '/assets/plans/home-plan6.png',
    communityCount: 3,
    series: "40' Series",
    specLevel: 'Signature',
    modelId: 'MODEL-2025-014',
    masterModelId: 'MASTER-2025-014',
    collection: ['Modern Collection'],
    seriesList: ["40' Series"],
    structureType: ['Single Family'],
    specificationLevel: ['Signature'],
    division: ['DFW'],
    description: 'Modern elevation with spa bath and smart home ready features for contemporary living.',
    bedrooms: 4,
    bathrooms: 3,
    halfBaths: 1,
    garageSpaces: 2,
    totalFinishedSqft: 2950,
    totalUnfinishedSqft: 850,
    width: "40'",
    depth: "60'",
    numberOfElevations: 5,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 185,
    floors: 2,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2025-014',
    permitIssued: '2/12/2025',
    permitExpires: '2/12/2028',
    governingBody: 'City of Allen',
    state: 'TX',
    adaCompliant: 'No',
    planFeatures: ['Modern elevation', 'Spa bath', 'Smart home ready'],
    architectOfRecord: 'Emerald Design Group',
    engineerOfRecord: 'Horizon Engineering',
    copyrightOwner: 'Emerald Design Group',
    maxBedrooms: 4,
    maxBathrooms: 3,
    maxHalfBaths: 1,
    maxTotalFinishedSqft: 3100,
    maxTotalUnfinishedSqft: 850,
    maxWidth: "40'",
    maxDepth: "60'",
    maxHeight: "38'",
    baseAreaUnderRoof: 2100,
    maxAreaUnderRoof: 2800,
    firstFloorSqft: 1700,
    secondFloorSqft: 1400,
    frontPorchSqft: 160,
    garageSqft: 800,
    minRoofPitch: '8/12',
    maxRoofPitch: '4/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Up',
    ownerRoomLocation: 'Up',
    baseGarageDoors: 1,
    maxGarageDoors: 1,
    maxGarageBay: 2,
    garageLocation: 'Front',
    baseFireplace: 1,
    maxFireplace: 1,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Brick/Stone'],
    doorTypes: ['6 Panel', 'Steel/Craftsman'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 6,
    baseExteriorDoors: 2,
    maxExteriorDoors: 2,
    baseInteriorDoors: 6,
    maxInteriorDoors: 8,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 16,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'waterview',
    name: 'The Waterview',
    beds: '3',
    baths: '2.5',
    sqft: '2,200 ft²',
    image: '/assets/plans/home-plan7.png',
    communityCount: 2,
    series: "25' Series",
    specLevel: 'Luxury',
    modelId: 'MODEL-2023-009',
    masterModelId: 'MASTER-2023-009',
    collection: ['Urban Collection'],
    seriesList: ["25' Series"],
    structureType: ['Townhome', 'Villa'],
    specificationLevel: ['Luxury'],
    division: ['DFW', 'Dallas'],
    description: 'Rooftop terrace, multi-level living with luxury finishes designed for urban lifestyles.',
    bedrooms: 3,
    bathrooms: 2,
    halfBaths: 1,
    garageSpaces: 2,
    totalFinishedSqft: 2200,
    totalUnfinishedSqft: 400,
    width: "25'",
    depth: "60'",
    numberOfElevations: 4,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 205,
    floors: 3,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2023-009',
    permitIssued: '9/1/2023',
    permitExpires: '9/1/2026',
    governingBody: 'City of Dallas',
    state: 'TX',
    adaCompliant: 'Partial',
    planFeatures: ['Rooftop terrace', 'Multi-level living', 'Luxury finishes'],
    architectOfRecord: 'JB Designs',
    engineerOfRecord: 'Apex Structural Engineering',
    copyrightOwner: 'JB Designs',
    maxBedrooms: 4,
    maxBathrooms: 3,
    maxHalfBaths: 1,
    maxTotalFinishedSqft: 2600,
    maxTotalUnfinishedSqft: 500,
    maxWidth: "28'",
    maxDepth: "60'",
    maxHeight: "45'",
    baseAreaUnderRoof: 1600,
    maxAreaUnderRoof: 2200,
    firstFloorSqft: 900,
    secondFloorSqft: 1700,
    frontPorchSqft: 120,
    garageSqft: 800,
    minRoofPitch: '8/12',
    maxRoofPitch: '4/12',
    roofConstructionType: 'Gable / Flat',
    laundryLocation: 'Up',
    ownerRoomLocation: 'Up',
    baseGarageDoors: 1,
    maxGarageDoors: 1,
    maxGarageBay: 2,
    garageLocation: 'Rear or Side',
    baseFireplace: 1,
    maxFireplace: 1,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Brick/Modern Accents'],
    doorTypes: ['6 Panel', 'Steel/Custom'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 6,
    baseExteriorDoors: 2,
    maxExteriorDoors: 2,
    baseInteriorDoors: 6,
    maxInteriorDoors: 8,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 14,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
  {
    id: 'elena',
    name: 'The Elena',
    beds: '4',
    baths: '3',
    sqft: '3,800 ft²',
    image: '/assets/plans/home-plan8.png',
    communityCount: 5,
    series: "60' Series",
    specLevel: 'Luxury',
    modelId: 'MODEL-2024-015',
    masterModelId: 'MASTER-2024-015',
    collection: ['Estate Collection'],
    seriesList: ["60' Series"],
    structureType: ['Single Family'],
    specificationLevel: ['Luxury'],
    division: ['DFW', 'Frisco'],
    description: 'Expansive owner\'s suite, hobby room, and courtyard create the ultimate single-story estate.',
    bedrooms: 4,
    bathrooms: 3,
    halfBaths: 1,
    garageSpaces: 3,
    totalFinishedSqft: 3800,
    totalUnfinishedSqft: 1100,
    width: "60'",
    depth: "70'",
    numberOfElevations: 5,
    foundationTypes: ['Slab'],
    costPerSquareFoot: 200,
    floors: 1,
    version: 1,
    buildingCode: '2021 IBC',
    permitNumber: 'PERM-DFW-2024-015',
    permitIssued: '4/18/2024',
    permitExpires: '4/18/2027',
    governingBody: 'City of Frisco',
    state: 'TX',
    adaCompliant: 'Partial',
    planFeatures: ['Expansive owner\'s suite', 'Hobby room', 'Courtyard'],
    architectOfRecord: 'Smith Architecture',
    engineerOfRecord: 'Horizon Engineering',
    copyrightOwner: 'Smith Architecture',
    maxBedrooms: 5,
    maxBathrooms: 4,
    maxHalfBaths: 2,
    maxTotalFinishedSqft: 3600,
    maxTotalUnfinishedSqft: 1100,
    maxWidth: "60'",
    maxDepth: "70'",
    maxHeight: "35'",
    baseAreaUnderRoof: 2600,
    maxAreaUnderRoof: 3500,
    firstFloorSqft: 3200,
    secondFloorSqft: 0,
    frontPorchSqft: 400,
    garageSqft: 220,
    minRoofPitch: '8/12',
    maxRoofPitch: '4/12',
    roofConstructionType: 'Gable',
    laundryLocation: 'Down',
    ownerRoomLocation: 'Down',
    baseGarageDoors: 2,
    maxGarageDoors: 2,
    maxGarageBay: 3,
    garageLocation: 'Side or Front',
    baseFireplace: 1,
    maxFireplace: 2,
    foundationQuantity: 1,
    exteriorFinish: ['Siding', 'Brick', 'Stone/Copper'],
    doorTypes: ['6 Panel', 'Copper/Custom'],
    windowTypes: ['Triple Pane'],
    differentWindowSizes: 8,
    baseExteriorDoors: 2,
    maxExteriorDoors: 3,
    baseInteriorDoors: 8,
    maxInteriorDoors: 10,
    wallConstructionType: ['2x6', '2x4'],
    minCeilingHeight: 9,
    maxCeilingHeight: 20,
    energyRating: 'LEED Gold',
    hvacType: 'Forced Air',
    plumbingType: ['Copper', 'PEX'],
  },
]

// Helper function to get plan by ID
export function getPlanById(id: string): PlanData | undefined {
  return plans.find(plan => plan.id === id)
}
