import { SpecItem } from './types';

export const globalConstructionSpecs: SpecItem[] = [
  // General Construction
  {
    id: 'g1',
    category: 'General Construction',
    subCategory: 'Concrete Strength',
    location: '',
    description: 'Concrete shall have a minimum compressive strength of 4,000 PSI at 28 days',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
  {
    id: 'g2',
    category: 'General Construction',
    subCategory: 'Structural Steel Grade',
    location: '',
    description: 'All structural steel shall conform to ASTM A992, Grade 50',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
  {
    id: 'g3',
    category: 'General Construction',
    subCategory: 'Masonry Unit Standards',
    location: '',
    description: 'Concrete masonry units (CMU) shall meet ASTM C90 standards',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
  {
    id: 'g4',
    category: 'General Construction',
    subCategory: 'Foundation',
    location: '',
    description: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },

  // Building Exterior
  {
    id: 'g5',
    category: 'Building Exterior',
    subCategory: 'Exterior Wall Cladding',
    location: '',
    description: 'Install fiber cement siding panels meeting ASTM C1186 Type A, Grade II',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
  {
    id: 'g6',
    category: 'Building Exterior',
    subCategory: 'Brick Masonry',
    location: '',
    description: 'Use modular clay brick meeting ASTM C216, Grade SW',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
  {
    id: 'g7',
    category: 'Building Exterior',
    subCategory: 'Exterior Paint',
    location: '',
    description: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
  {
    id: 'g8',
    category: 'Building Exterior',
    subCategory: 'Trim',
    location: '',
    description: 'Apply two coats of acrylic latex exterior paint with minimum 10-year warranty',
    region: 'Region1, Region2, Region 8',
    division: 'DFW, Houston',
    community: 'Community 1, Community 2, Community 3',
  },
];
