import { SpecItem } from './types';

export const globalConstructionSpecs: SpecItem[] = [
  // General Construction
  {
    id: 'g1',
    category: 'General Construction',
    subCategory: 'Engineering Specifications',
    location: '',
    description: '140 mph Wind Rating, Fully Enclosed',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g2',
    category: 'General Construction',
    subCategory: 'Foundation',
    location: '',
    description: 'Slab on grade, reinforced footers and steel with vapor barrier and min 2500 psi per engineered drawings',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g3',
    category: 'General Construction',
    subCategory: 'Structural Tie Down System',
    location: '',
    description: 'Threaded Rods and Simpson Metal Straps and hold downs per Engineering (applicable code or greater)',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g4',
    category: 'General Construction',
    subCategory: 'House Wrap',
    location: '',
    description: "Installed Over 2x Framed walls with 1' Overlap over Block wall. Tape window sills & around all windows",
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // Building Exterior
  {
    id: 'g5',
    category: 'Building Exterior',
    subCategory: 'Front Exterior Finish',
    location: '',
    description: 'Textured Cement Stucco or Cement Fiber Siding - per plan',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g6',
    category: 'Building Exterior',
    subCategory: 'Decorative Trim Bands',
    location: '',
    description: 'Raised Stucco Bands per plan / Raise 2# tuff coat foam bands per plan / Hardie trim accents per plan',
    region: 'Texas',
    division: 'DFW',
    community: 'Whispering Hills, The Pines',
  },

  // Insulation
  {
    id: 'g7',
    category: 'Insulation',
    subCategory: 'Exterior Wall Insulation',
    location: '',
    description: '(First Floor) R-4.2 Fi-Foil on exterior block walls with R=3.81 per inch (Second Floor) R= 3.81 per inch open cell spray foam insulation Icynene or equal',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g8',
    category: 'Insulation',
    subCategory: 'Ceiling Insulation',
    location: '',
    description: '5" thick open cell spray foam insulation Icynene or equal for all ceilings encapsulated at top chord of truss',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // Roofing
  {
    id: 'g9',
    category: 'Roofing',
    subCategory: 'Roof Dry-in',
    location: '',
    description: 'Palisade Synthetic or Meritage Approved Equiv. with Perm Rating of .4 or less (Shingle), Boral Peel & Stick (Tile)',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g10',
    category: 'Roofing',
    subCategory: 'Roof Shingle',
    location: '',
    description: '30 Year Architectural Shingle',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // General Plumbing
  {
    id: 'g11',
    category: 'General Plumbing',
    subCategory: 'Potable Water Pipe',
    location: '',
    description: 'Cross-Linked Polyethylene (PEX or Aquapex) PEX and PEX insert fittings manufactured by Dura-Line meeting ASTM F-877',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g12',
    category: 'General Plumbing',
    subCategory: 'Water Heater',
    location: '',
    description: '50 Gallon with 3.5 baths/(2) 50 Gallon with 4+ baths',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // Cabinetry/Tops
  {
    id: 'g13',
    category: 'Cabinetry/Tops',
    subCategory: 'Kitchen Upper Cabinet Dimension',
    location: '',
    description: '36" high uppers with cabinet over refrigerator',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g14',
    category: 'Cabinetry/Tops',
    subCategory: 'Master Bath Vanity Top',
    location: '',
    description: 'Granite',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // Drywall
  {
    id: 'g15',
    category: 'Drywall',
    subCategory: 'Interior Walls',
    location: '',
    description: '1/2" Regular Drywall - Orange Peel Texture',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g16',
    category: 'Drywall',
    subCategory: 'Interior Ceilings',
    location: '',
    description: '1/2" HD or 5/8" Ceiling Drywall - Knockdown Texture',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // Interior Millwork
  {
    id: 'g17',
    category: 'Interior Millwork',
    subCategory: 'Front Entry Door',
    location: '',
    description: 'Typical: 8\'0" Fiberglass, 6 panel SMFG (plans w/Shingle Roof)',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g18',
    category: 'Interior Millwork',
    subCategory: 'Baseboard',
    location: '',
    description: 'Std 3 1/4" colonial base board',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },

  // Exterior Flatwork
  {
    id: 'g19',
    category: 'Exterior Flatwork',
    subCategory: 'Driveway',
    location: '',
    description: 'Paved Driveway to match the full length of the garage door only',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g20',
    category: 'Exterior Flatwork',
    subCategory: 'Front Porch',
    location: '',
    description: 'Acrylic Deck Paint with knockdown texture finish',
    region: 'Texas',
    division: 'DFW',
    community: 'Whispering Hills, The Pines',
  },

  // Landscaping
  {
    id: 'g21',
    category: 'Landscaping',
    subCategory: 'Sod',
    location: '',
    description: 'Per community specifications',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
  {
    id: 'g22',
    category: 'Landscaping',
    subCategory: 'Irrigation',
    location: '',
    description: 'Per community specifications',
    region: 'Texas',
    division: 'DFW, Houston',
    community: 'Whispering Hills, Riverside Estates, The Pines',
  },
];
