import { SpecItem } from './types';

export const constructionSpecs: SpecItem[] = [
  // General Construction
  {
    id: '1',
    category: 'General Construction',
    subCategory: 'Concrete Strength',
    location: 'Foundation/Slabs',
    description: 'Concrete shall have a minimum compressive strength of 4,000 PSI',
    manufacturer: 'Quikrete',
    model: 'QC-4000',
    color: 'Gray',
    quantity: '100 CY',
    warranty: '10 years',
  },
  {
    id: '2',
    category: 'General Construction',
    subCategory: 'Structural Steel Grade',
    location: 'Structural Framework',
    description: 'All structural steel shall conform to ASTM A992',
    manufacturer: 'Nucor',
    model: 'A992-GR50',
    color: 'Mill Finish',
    quantity: '50 tons',
    warranty: '25 years',
  },
  {
    id: '3',
    category: 'General Construction',
    subCategory: 'Masonry Unit Standards',
    location: 'Exterior Walls',
    description: 'Concrete masonry units (CMU) shall meet ASTM C90',
    manufacturer: 'Oldcastle APG',
    model: 'CMU-8x8x16',
    color: 'Natural Gray',
    quantity: '5,000 units',
    warranty: '15 years',
  },

  // Building Exterior
  {
    id: '4',
    category: 'Building Exterior',
    subCategory: 'Exterior Wall Cladding',
    location: 'Exterior Walls',
    description: 'Install fiber cement siding panels',
    manufacturer: 'James Hardie',
    model: 'HardiePlank',
    color: 'Arctic White',
    quantity: '2,500 SF',
    warranty: '30 years',
  },
  {
    id: '5',
    category: 'Building Exterior',
    subCategory: 'Brick Masonry',
    location: 'Exterior Facade',
    description: 'Use modular clay brick meeting ASTM C216',
    manufacturer: 'Boral',
    model: 'Modular-STD',
    color: 'Colonial Red',
    quantity: '8,000 units',
    warranty: '50 years',
  },
  {
    id: '6',
    category: 'Building Exterior',
    subCategory: 'Exterior Paint',
    location: 'Exterior Walls/Trim',
    description: 'Apply two coats of acrylic latex paint',
    manufacturer: 'Sherwin-Williams',
    model: 'Duration',
    color: 'Custom Match',
    quantity: '150 gal',
    warranty: '15 years',
  },
  {
    id: '7',
    category: 'Building Exterior',
    subCategory: 'Roofing Membrane',
    location: 'Roof',
    description: 'Install a fully adhered EPDM roofing system',
    manufacturer: 'Firestone',
    model: 'RubberGard EPDM',
    color: 'Black',
    quantity: '10,000 SF',
    warranty: '20 years',
  },

  // Interior Finishes
  {
    id: '8',
    category: 'Interior Finishes',
    subCategory: 'Ceramic Tile Flooring',
    location: 'Restrooms/Kitchens',
    description: 'Install 12"x12" porcelain ceramic tile',
    manufacturer: 'Daltile',
    model: 'Keystones',
    color: 'Biscuit',
    quantity: '1,200 SF',
    warranty: 'Lifetime',
  },
  {
    id: '9',
    category: 'Interior Finishes',
    subCategory: 'Carpet Flooring',
    location: 'Offices/Common Areas',
    description: 'Use nylon broadloom carpet',
    manufacturer: 'Shaw',
    model: 'Philadelphia Commercial',
    color: 'Charcoal',
    quantity: '5,000 SF',
    warranty: '10 years',
  },
];
