import { SpecItem } from './types';

export const constructionSpecs: SpecItem[] = [
  // General Construction
  {
    id: '1',
    category: 'General Construction',
    subCategory: 'Foundation',
    location: 'Foundation',
    description: 'Slab on grade, reinforced footers and steel with vapor barrier and min 2500 psi per engineered drawings',
    manufacturer: 'Local Supplier',
    model: 'SOG-2500',
    color: 'Natural',
    quantity: '1 per home',
    warranty: '10 years',
  },
  {
    id: '2',
    category: 'General Construction',
    subCategory: 'Termite Protection',
    location: 'Perimeter',
    description: 'Boracare perimeter treatment',
    manufacturer: 'Boracare',
    model: 'BOR-PT100',
    color: 'Clear',
    quantity: '1 treatment',
    warranty: '5 years',
  },
  {
    id: '3',
    category: 'General Construction',
    subCategory: 'Roof Trusses',
    location: 'Roof Structure',
    description: 'Engineered Roof Truss System',
    manufacturer: 'Truss Systems Inc',
    model: 'ERT-2024',
    color: 'Natural Wood',
    quantity: 'Per plan',
    warranty: '25 years',
  },

  // Building Exterior
  {
    id: '4',
    category: 'Building Exterior',
    subCategory: 'Front Exterior Finish',
    location: 'Front Elevation',
    description: 'Textured Cement Stucco or Cement Fiber Siding - per plan',
    manufacturer: 'Hardie',
    model: 'HardiePlank',
    color: 'Per Selection',
    quantity: '1,200 SF',
    warranty: '30 years',
  },
  {
    id: '5',
    category: 'Building Exterior',
    subCategory: 'Fascia',
    location: 'Roof Edge',
    description: '6" Aluminum Fascia',
    manufacturer: 'Alsco Metals',
    model: 'ALF-6',
    color: 'White',
    quantity: '180 LF',
    warranty: '20 years',
  },
  {
    id: '6',
    category: 'Building Exterior',
    subCategory: 'Soffit',
    location: 'Eaves',
    description: 'Aluminum Triple 4 Soffit - Non Vent',
    manufacturer: 'Alsco Metals',
    model: 'T4-NV',
    color: 'White',
    quantity: '400 SF',
    warranty: '20 years',
  },

  // Roofing
  {
    id: '7',
    category: 'Roofing',
    subCategory: 'Roof Shingle',
    location: 'Roof',
    description: '30 Year Architectural Shingle',
    manufacturer: 'GAF',
    model: 'Timberline HDZ',
    color: 'Charcoal',
    quantity: '25 squares',
    warranty: '30 years',
  },
  {
    id: '8',
    category: 'Roofing',
    subCategory: 'Drip Edge',
    location: 'Roof Edge',
    description: '6" - 26 gauge Painted Drip Edge',
    manufacturer: 'Amerimax',
    model: 'DE-626',
    color: 'Brown',
    quantity: '200 LF',
    warranty: '15 years',
  },

  // Windows & Garage Door
  {
    id: '9',
    category: 'Windows & Garage Door',
    subCategory: 'Windows',
    location: 'All Elevations',
    description: 'MI Vinyl or Ply Gem Low E Glass (Grids Only on Front Elevation)',
    manufacturer: 'Ply Gem',
    model: 'PG-LE200',
    color: 'White',
    quantity: '18 units',
    warranty: '20 years',
  },
  {
    id: '10',
    category: 'Windows & Garage Door',
    subCategory: 'Garage Door',
    location: 'Garage',
    description: "Insulated 16' x 7' Garage Door, 8' Single Garage Door on 3rd bay if applicable",
    manufacturer: 'Clopay',
    model: 'Classic Steel',
    color: 'White',
    quantity: '1-2 units',
    warranty: '10 years',
  },
  {
    id: '11',
    category: 'Windows & Garage Door',
    subCategory: 'Garage Door Opener',
    location: 'Garage',
    description: '1/2 HP Door Opener with 2 Remote Controls (per door)',
    manufacturer: 'Chamberlin',
    model: 'C450',
    color: 'Gray',
    quantity: '1-2 units',
    warranty: '5 years',
  },

  // HVAC
  {
    id: '12',
    category: 'HVAC',
    subCategory: 'Equipment',
    location: 'Utility Area',
    description: 'Carrier Single Stage',
    manufacturer: 'Carrier',
    model: '24ACC636',
    color: 'Gray',
    quantity: '1 system',
    warranty: '10 years',
  },
  {
    id: '13',
    category: 'HVAC',
    subCategory: 'Thermostat',
    location: 'Hallway',
    description: 'Nest Smart Thermostat',
    manufacturer: 'Nest',
    model: 'Learning 3rd Gen',
    color: 'Stainless Steel',
    quantity: '1 unit',
    warranty: '2 years',
  },

  // Plumbing Fixtures
  {
    id: '14',
    category: 'Plumbing Fixtures',
    subCategory: 'Kitchen Sink',
    location: 'Kitchen',
    description: '50/50 Stainless Steel Drop-In',
    manufacturer: 'Elkay',
    model: 'DLR332210',
    color: 'Stainless Steel',
    quantity: '1 unit',
    warranty: 'Lifetime',
  },
  {
    id: '15',
    category: 'Plumbing Fixtures',
    subCategory: 'Master Bath Toilet',
    location: 'Master Bath',
    description: 'Elongated Front Dual Flush Toilet (Std Height)',
    manufacturer: 'Kohler',
    model: 'Wellworth K-3988',
    color: 'White',
    quantity: '1 unit',
    warranty: '1 year',
  },

  // Flooring
  {
    id: '16',
    category: 'Flooring / Bath Accessories/ Sills',
    subCategory: 'Kitchen',
    location: 'Kitchen',
    description: '12" Base Daltile Tile',
    manufacturer: 'Daltile',
    model: 'Keystones D311',
    color: 'Almond',
    quantity: '180 SF',
    warranty: 'Lifetime',
  },
  {
    id: '17',
    category: 'Flooring / Bath Accessories/ Sills',
    subCategory: 'Family Room',
    location: 'Family Room',
    description: 'Standard Shaw Carpet. Color Per Selection',
    manufacturer: 'Shaw',
    model: 'Charmed Hues',
    color: 'Sandstone',
    quantity: '400 SF',
    warranty: '25 years',
  },

  // Paint
  {
    id: '18',
    category: 'Paint',
    subCategory: 'Interior Walls',
    location: 'All Interior',
    description: 'Sherwin Williams Painter\'s Edge - One Full Coat Sprayed and Back Rolled',
    manufacturer: 'Sherwin Williams',
    model: 'Painter\'s Edge',
    color: 'Agreeable Gray',
    quantity: '20 gal',
    warranty: '5 years',
  },
  {
    id: '19',
    category: 'Paint',
    subCategory: 'Interior Doors and Trim',
    location: 'All Doors/Trim',
    description: 'Sherwin Williams Promar 400 Zero VOC Semi Gloss',
    manufacturer: 'Sherwin Williams',
    model: 'Promar 400',
    color: 'Extra White',
    quantity: '8 gal',
    warranty: '5 years',
  },

  // Appliances
  {
    id: '20',
    category: 'Appliances',
    subCategory: 'Dishwasher',
    location: 'Kitchen',
    description: 'Energy Star DishWasher - SS',
    manufacturer: 'Whirlpool',
    model: 'WDT750SAKZ',
    color: 'Stainless Steel',
    quantity: '1 unit',
    warranty: '1 year',
  },
  {
    id: '21',
    category: 'Appliances',
    subCategory: 'Microwave',
    location: 'Kitchen',
    description: 'Vented Microwave above Stove Top - SS',
    manufacturer: 'Whirlpool',
    model: 'WMH31017HS',
    color: 'Stainless Steel',
    quantity: '1 unit',
    warranty: '1 year',
  },

  // Door Hardware
  {
    id: '22',
    category: 'Door Hardware',
    subCategory: 'Front Entry Door Hardware',
    location: 'Front Entry',
    description: 'Wyze Smart Lock system',
    manufacturer: 'Wyze',
    model: 'Lock Bolt',
    color: 'Matte Black',
    quantity: '1 unit',
    warranty: '1 year',
  },

  // Specialties
  {
    id: '23',
    category: 'Specialties',
    subCategory: 'Bathroom Towel Bars',
    location: 'All Baths',
    description: 'Moen Mason, Brushed Nickel finish',
    manufacturer: 'Moen',
    model: 'Mason DN0724BN',
    color: 'Brushed Nickel',
    quantity: '4 units',
    warranty: 'Lifetime',
  },
  {
    id: '24',
    category: 'Specialties',
    subCategory: 'Master Bath Mirrors',
    location: 'Master Bath',
    description: '36" x 96" HD Backlit',
    manufacturer: 'Keonjinn',
    model: 'LED-3696',
    color: 'Silver Frame',
    quantity: '1 unit',
    warranty: '3 years',
  },
];
